### PR TITLE
Move old v3 airgapped documentation to v4.

### PR DESCRIPTION
**Pull request by bergmannf**
Most of the documentation remains the same.

The section about configuring the `mirror` in `Velum` is replaced by
configuring it on each host by adding a configuration file.

Right now it seems however that authentication in the docker registry
breaks with `crio`, so this is noted especially.

# TODO:

It seems also that most of the links to the `rmt` documentation are broken,
but replacing them with up-to-date ones will just link to the documentation
overview.

### CODE REVIEW

**Comment by bergmannf** [comment]
I have some more developer-focused documentation about testing this here: https://github.com/SUSE/avant-garde/issues/864#issuecomment-539009064

I am not sure if integrating parts of this make sense.

**Comment by r0ckarong** [comment]
> I have some more developer-focused documentation about testing this here: [SUSE/avant-garde#864 (comment)](https://github.com/SUSE/avant-garde/issues/864#issuecomment-539009064)
> 
> I am not sure if integrating parts of this make sense.

@bergmannf Are there any major changes that are reflected in your testing docs that need to be changed in the new version or did you already include that in the commit?

**Comment by r0ckarong** [comment]
@flavio @ereslibre Parts of these instructions still refer to SLES 12 for the registry mirror. Is this limitation still in place?

**Comment by innobead** [comment]
cc @c3y1huang please help review. thanks.

**Comment by bergmannf** [comment]
@r0ckarong The changes needed (only the new `registry` configuration) were already part of the PR.

**Comment by flavio** [comment]
> @flavio @ereslibre Parts of these instructions still refer to SLES 12 for the registry mirror. Is this limitation still in place?

I don't remember why we had this limitation in place in the beginning :sweat_smile: 

If RMT can be deployed on top of SLE15 SP1, then let's move to it. Even better, we could make the deployment instructions generic and do not mention which version of SLES we should be using.

In the end we just need a container engine, which is something we are shipping to all the versions of SLES. The hard requirement comes from RMT, which has its own manual.

**Comment by r0ckarong** [comment]
> > @flavio @ereslibre Parts of these instructions still refer to SLES 12 for the registry mirror. Is this limitation still in place?
> 
> I don't remember why we had this limitation in place in the beginning sweat_smile
> 
> If RMT can be deployed on top of SLE15 SP1, then let's move to it. Even better, we could make the deployment instructions generic and do not mention which version of SLES we should be using.
> 
> In the end we just need a container engine, which is something we are shipping to all the versions of SLES. The hard requirement comes from RMT, which has its own manual.

I read through it again and the point here was that the registry container image was only available on SLES 12 repos.

@jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?

https://github.com/bergmannf/doc-caasp/blame/airgapped-documentation/adoc/deployment-airgapped.adoc#L510

**Comment by Martin-Weiss** [comment]
> @jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?

Not sure what you mean with "sles15 container registry" - but just recently used this: registry.suse.com/sles12/registry:2.6.2

And we have something in https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#book-sles-docker / https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-registry-installation where we could refer to (even though I assume packagehub is not supported but registry image on registry.suse.com is supported - so also this SLES 15 SP1 guide might require some fixes / changes).

**Comment by r0ckarong** [comment]
> > @jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?
> 
> Not sure what you mean with "sles15 container registry" - but just recently used this: registry.suse.com/sles12/registry:2.6.2

The `/sles12/` part is why I'm asking. To me that implies this is meant to be used with SLES12 but maybe I misunderstand why it's structured this way.
> 
> And we have something in https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#book-sles-docker / https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-registry-installation where we could refer to (even though I assume packagehub is not supported but registry image on registry.suse.com is supported - so also this SLES 15 SP1 guide might require some fixes / changes).

Correct, PackageHub isn't officially supported so we have to use a supported image from the registry.

If you find changes that are needed for the SLES 15 SP1 docs please report them at https://github.com/SUSE/doc-sle

**Comment by Martin-Weiss** [comment]
> 
> 
> > > @jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?
> > 
> > 
> > Not sure what you mean with "sles15 container registry" - but just recently used this: registry.suse.com/sles12/registry:2.6.2
> 
> The `/sles12/` part is why I'm asking. To me that implies this is meant to be used with SLES12 but maybe I misunderstand why it's structured this way.

Yeah - the structure, versioning and naming on the registry is a bit confusing and unclear. Hope this gets better, soon.

> 
> > And we have something in https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#book-sles-docker / https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-registry-installation where we could refer to (even though I assume packagehub is not supported but registry image on registry.suse.com is supported - so also this SLES 15 SP1 guide might require some fixes / changes).
> 
> Correct, PackageHub isn't officially supported so we have to use a supported image from the registry.
> 
> If you find changes that are needed for the SLES 15 SP1 docs please report them at https://github.com/SUSE/doc-sle

Already done - just think for CaaSP we should refer to the SLES documentation for registry and portus as this is part of SLES and not part of CaaSP (AFAIK).

**Comment by jordimassaguerpla** [comment]
> > > > @jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?
> > > 
> > > 
> > > Not sure what you mean with "sles15 container registry" - but just recently used this: registry.suse.com/sles12/registry:2.6.2
> > 
> > 
> > The `/sles12/` part is why I'm asking. To me that implies this is meant to be used with SLES12 but maybe I misunderstand why it's structured this way.
> 
> Yeah - the structure, versioning and naming on the registry is a bit confusing and unclear. Hope this gets better, soon.
> 
> > > And we have something in https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#book-sles-docker / https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-registry-installation where we could refer to (even though I assume packagehub is not supported but registry image on registry.suse.com is supported - so also this SLES 15 SP1 guide might require some fixes / changes).
> > 
> > 
> > Correct, PackageHub isn't officially supported so we have to use a supported image from the registry.
> > If you find changes that are needed for the SLES 15 SP1 docs please report them at https://github.com/SUSE/doc-sle
> 
> Already done - just think for CaaSP we should refer to the SLES documentation for registry and portus as this is part of SLES and not part of CaaSP (AFAIK).

Exactly. The distribution image is part of SLE. Right now we have a SLES12SP3 based image, the one Martin pointed out.

**Comment by c3y1huang** [comment]
> > > > > @jordimassaguerpla Do we have the docker registry image in the sles15 container registry now?
> > > > 
> > > > 
> > > > Not sure what you mean with "sles15 container registry" - but just recently used this: registry.suse.com/sles12/registry:2.6.2
> > > 
> > > 
> > > The `/sles12/` part is why I'm asking. To me that implies this is meant to be used with SLES12 but maybe I misunderstand why it's structured this way.
> > 
> > 
> > Yeah - the structure, versioning and naming on the registry is a bit confusing and unclear. Hope this gets better, soon.
> > > > And we have something in https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#book-sles-docker / https://documentation.suse.com/sles/15-SP1/single-html/SLES-dockerquick/#sec-docker-registry-installation where we could refer to (even though I assume packagehub is not supported but registry image on registry.suse.com is supported - so also this SLES 15 SP1 guide might require some fixes / changes).
> > > 
> > > 
> > > Correct, PackageHub isn't officially supported so we have to use a supported image from the registry.
> > > If you find changes that are needed for the SLES 15 SP1 docs please report them at https://github.com/SUSE/doc-sle
> > 
> > 
> > Already done - just think for CaaSP we should refer to the SLES documentation for registry and portus as this is part of SLES and not part of CaaSP (AFAIK).
> 
> Exactly. The distribution image is part of SLE. Right now we have a SLES12SP3 based image, the one Martin pointed out.

I've [PR](https://github.com/SUSE/doc-caasp/pull/560) to updated the guide to use `registry.suse.com/caasp/v4/registry:2.6.2` instead of `registry.suse.com/sles12/registry:2.6.2`.

**Comment by Martin-Weiss** [comment]
> I've PR to updated the guide to use registry.suse.com/caasp/v4/registry:2.6.2 instead of registry.suse.com/sles12/registry:2.6.2.

--> why do we have this image twice? Is this the same image or are these different ones and who is going to support these? (SUSE SLE or SUSE CaaSP team)?

**Comment by innobead** [comment]
> > I've PR to updated the guide to use registry.suse.com/caasp/v4/registry:2.6.2 instead of registry.suse.com/sles12/registry:2.6.2.
> 
> --> why do we have this image twice? Is this the same image or are these different ones and who is going to support these? (SUSE SLE or SUSE CaaSP team)?

@jordimassaguerpla could you help check why we have registry.suse.com/caasp/v4/registry:2.6.2? I think we just need to use sles one. 

@c3y1huang we don't need to change the `registry.suse.com/sles12/registry:2.6.2`. Let's just keep the one referred from SLES doc, but thanks for the catch.

**Comment by jordimassaguerpla** [comment]
> > I've PR to updated the guide to use registry.suse.com/caasp/v4/registry:2.6.2 instead of registry.suse.com/sles12/registry:2.6.2.
> 
> --> why do we have this image twice? Is this the same image or are these different ones and who is going to support these? (SUSE SLE or SUSE CaaSP team)?

Use the SLES one.

The CaaSP one was released as part of beta1. See this containers is labeled as Beta1 in registry.suse.com.

The SLES one should be supported as part of the containers module (which is supported by CaaSP Team).

**Pull request merged**
