### PR TITLE
Oidc docs

### PR DESCRIPTION
**Pull request by dannysauer**
Add external OIDC connector section.  Probably should squash those commits. :D

### CODE REVIEW

**Comment by dannysauer** [comment]
This morning I fixed the duplicated identifiers causing Travis to fail, but I don't seem to have access to push.  I'm not sure why.  Help, @r0ckarong :D

**Comment by r0ckarong** [comment]
> This morning I fixed the duplicated identifiers causing Travis to fail, but I don't seem to have access to push. I'm not sure why. Help, @r0ckarong :D

I switched off write access to the repo for anyone but admins. I will turn it on for you until this is resolved. We will probably switch to a fork based PR workflow soon. Sorry for causing the inconvenience.

**Comment by dannysauer** [comment]
I'm ok with making a fork & new PR now if you'd prefer; that's pretty simple.

**Comment by r0ckarong** [comment]
I switched your write access back on for now. It's easier than starting over with this PR.

The next one will be fork based then.

**Comment by nkoranova** [comment]
@dannysauer sorry we left this hanging here - I will review and merge it ASAP, if the info is still relevant. Is it? :)

**Comment by dannysauer** [comment]
Yeah, it's still relevant. We just had a bug report from a v3 customer having difficulty configuring OIDC last week, in fact. :)

**Pull request merged**
