### PR TITLE
Custom certificates for dex and gangway (Closes #619)

### LINKED ISSUE #619: [doc] 4.9.6  Manual Certificate Renewal -> document what is required to use custom certificates for dex and gangway
4.9.6  Manual Certificate Renewal

https://susedoc.github.io/doc-caasp/master/caasp-admin/single-html/#_manual_certificate_renewal

----
Could we document what steps are required to replace the dex and gangway certificates with customer provided ones that are NOT signed by the kubernetes CA?

Many customers already have a certificate Authority and they want to create and use the certs using this CA and not using the kubernetes CA. It is also not possible to create an intermediate CA or copy the private key of that CA to the CaaSP system to create certificates signed by the "foreign" CA during skuba or kubeadm processes.

But - as dex and gangway are end-user visible - the certificates used there should be signed using the customers CA.

### PR DESCRIPTION
**Pull request by jenting**
# Make sure it's tested
*Technical writers will not always be able to verify the implementation!*

Any PR opened is assumed to have been verified by QA if not designated by comments or labels otherwise. Please make sure you have tested the changes and included any information that a user would require to use the documentation.

# Describe your changes

1. Add detailed steps on how to replace Dex & Gangway certificate after cluster deploy.
2. Add note that the customer replace Dex & Gangway certificate signed by custom CA certificate would be replaced after `skuba addon upgrade apply` if the addon upgrade includes Dex or Gangway.

Fix #619

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:

# Enable maintainer updates
Please enable maintainer updates so we can push commits into your branch to make collaboration and reviews easier.

# Do not force push your branch
Please avoid force pushing to branches that are subject of pull requests. Force pushing breaks maintainer commits in many cases and is very hard (if not impossible) to untangle for backporting.

# Labels
Please set any (and all) appropriate labels that describe the status of the PR.

| **Label** | **Description** |
| --- | --- |
| P1 | PR should be worked on and merged as soon as possible |
| Blocked | Work can not proceed because other work has not been completed, PR can not be merged (code has not been merged but documentation is ready) |
| On-Hold | Underlying work is completed but the PR should not be merged |
| ReleaseNotes | User interaction is required after the introduction of this change and the change must be mentioned in the release notes |
| v3/v4/v4.x | Which version of the release the PR should be merged into, this can be multiple versions, please set the "Backport" label if it needs to go into a previous release |
| Needs Review | Some details of the PR are known to be incomplete and must be discussed with other engineers before merging (if possible assign reviewers or cc mention in comments), PR can not be merged |

### CODE REVIEW

**Comment by innobead** [comment]
@jenting is this still blocked or ready to review?

**Comment by jenting** [comment]
> @jenting is this still blocked or ready to review?

Blocked. Two reasons:
1. Due to kustomize proposed, the doc need to updated again on how to deploy the custom certificate befter bootstrap.
2. At 4.0, dex + gangway certificate rotated when node upgrade. But after `skuba addon [plan|apply]` proposed, dex + gangway certificate rotated when addon upgrade. For this, I wish to add the certificate management for skuba (need to file RFC in my opinion)

**Comment by r0ckarong** [comment]
@innobead @jenting Does the pushed commits remove the blockers from your side?

**Comment by r0ckarong** [comment]
cc @mdarnell-suse

**Comment by jenting** [comment]
> @innobead @jenting Does the pushed commits remove the blockers from your side?

Let's focus on the current skuba supported, and will enhance this chapter once we have kustomize and skuba certificate management support.

Also, I will create another PR to consolidate self-signed or trusted certificate authority. Right now, three parts include the same thing.
  - admin-security-certificates.adoc
  - admin-monitoring-stack.adoc
  - admin-software-installation.adoc

**Comment by r0ckarong** [comment]
> But I don't know which is the best chapter to put the consolidated doc, do we have the knowledge base for caasp document @r0ckarong ? Or could we just reference to existed SUSE knowledge base https://www.suse.com/support/kb/doc/?id=7023144 in the chapters which need a certificate?

I think the best way to do this is to create a new chapter detailing the cert creation in `admin-security-certificates.adoc` for now and then linking from the other articles to that. Since those are all part of the admin guide you can use the asciidoc cross-reference/anchor format.

https://asciidoctor.org/docs/user-manual/#inter-document-cross-references

**Comment by jenting** [comment]
> > But I don't know which is the best chapter to put the consolidated doc, do we have the knowledge base for caasp document @r0ckarong ? Or could we just reference to existed SUSE knowledge base https://www.suse.com/support/kb/doc/?id=7023144 in the chapters which need a certificate?
> 
> I think the best way to do this is to create a new chapter detailing the cert creation in `admin-security-certificates.adoc` for now and then linking from the other articles to that. Since those are all part of the admin guide you can use the asciidoc cross-reference/anchor format.
> 
> https://asciidoctor.org/docs/user-manual/#inter-document-cross-references

Okay. And is it a good practice to link the cert create to existed SUSE knowledge base URL or should we write our own cert create in the doc?

**Comment by Martin-Weiss** [comment]
Just had a quick look at the TID mentioned (https://www.suse.com/support/kb/doc/?id=7023144) but that unfortunately does not have the details about required or recommended subject alternative names.
I believe we should also cover the required subject alternative names topic.

**Comment by jenting** [comment]
Make sense, thanks @Martin-Weiss

**Comment by r0ckarong** [comment]
> > > But I don't know which is the best chapter to put the consolidated doc, do we have the knowledge base for caasp document @r0ckarong ? Or could we just reference to existed SUSE knowledge base https://www.suse.com/support/kb/doc/?id=7023144 in the chapters which need a certificate?
> > 
> > 
> > I think the best way to do this is to create a new chapter detailing the cert creation in `admin-security-certificates.adoc` for now and then linking from the other articles to that. Since those are all part of the admin guide you can use the asciidoc cross-reference/anchor format.
> > https://asciidoctor.org/docs/user-manual/#inter-document-cross-references
> 
> Okay. And is it a good practice to link the cert create to existed SUSE knowledge base URL or should we write our own cert create in the doc?

If this is a SUSE created instruction vetted by the security team then I would think linking to the knowledge base is better. It has the downside that you have to jump outside of the docs workflow to finish this procedure. Please link to the knowledge base.

**Comment by jenting** [comment]
@r0ckarong As @Martin-Weiss said, the KB doc does not include how to add SAN into the certificate. So, I recommended not to link to the KB doc.
I had filed the PR #638 to addressing add SAN into the certificate, also consolidate the certificate generation into one.

**Comment by r0ckarong** [comment]
> @r0ckarong As @Martin-Weiss said, the KB doc does not include how to add SAN into the certificate. So, I recommended not to link to the KB doc.
> I had filed the PR #638 to addressing add SAN into the certificate, also consolidate the certificate generation into one.

So this topic will completely covered with the two PRs? Then I will merge them.

**Comment by jenting** [comment]
> > @r0ckarong As @Martin-Weiss said, the KB doc does not include how to add SAN into the certificate. So, I recommended not to link to the KB doc.
> > I had filed the PR #638 to addressing add SAN into the certificate, also consolidate the certificate generation into one.
> 
> So this topic will completely covered with the two PRs? Then I will merge them.

Yes, and I will add one more PR add anchor linked to create certificate l.

**Pull request merged**
