### PR TITLE
Add note about rebooting masters

### PR DESCRIPTION
**Pull request by dannysauer**
Tiny change for a large discussion. :D 

Here's a proposed addition adding an extra step to reboot the master nodes after applying the new CA certificates.  Feel free to change the wording completely or move it around the document. :)

### CODE REVIEW

**Comment by r0ckarong** [comment]
Could you enlighten me which discussion you are referring to? The wording itself sounds right to me but I'm missing the context to understand which problem it solves and if we need to change something else.

**Comment by dannysauer** [comment]
@r0ckarong This may not need to be done, given the direction shift doc'd in issue SUSE/caasp-playground#171.  It looks like we're going to try to make the service restarts / reboot automatic with Salt after all, potentially rendering this doc update unnecessary. :)  I'll update the PR in a day or two based on the outcome of resolving that issue.

**Comment by r0ckarong** [comment]
@dannysauer I'll put it on hold. If this resolves itself just close the PR.

**Comment by dannysauer** [comment]
Sorry; I could've sworn I closed this as unnecessary before.  Closing it now. :)

**Pull request closed without merging**
