### PR TITLE
Apply temporarily reverted replicas management to deployment reqs

### PR DESCRIPTION
**Pull request by r0ckarong**
Puts back the content reverted in #693 once package is ready.

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
blocked on https://github.com/SUSE/skuba/pull/951 and https://github.com/SUSE/avant-garde/issues/1093

**Comment by c3y1huang** [comment]
https://github.com/SUSE/skuba/pull/951 merged.

**Comment by r0ckarong** [comment]
@jordimassaguerpla Can this be merged now?

**Comment by jordimassaguerpla** [comment]
Hi @r0ckarong . Code is in for 4.2.0 https://github.com/SUSE/avant-garde/issues/1093 . So please hold it until we have the go from QA.

**Comment by c3y1huang** [comment]
> Hi @r0ckarong . Code is in for 4.2.0 [SUSE/avant-garde#1093](https://github.com/SUSE/avant-garde/issues/1093) . So please hold it until we have the go from QA.

@jordimassaguerpla , I believe the fix had been tested  [here](https://github.com/SUSE/skuba/pull/951) by @maximenoel8 and @thehejik. Are we waiting for other go from QA?

**Comment by jordimassaguerpla** [comment]
> > Hi @r0ckarong . Code is in for 4.2.0 [SUSE/avant-garde#1093](https://github.com/SUSE/avant-garde/issues/1093) . So please hold it until we have the go from QA.
> 
> @jordimassaguerpla , I believe the fix had been tested [here](https://github.com/SUSE/skuba/pull/951) by @maximenoel8 and @thehejik. Are we waiting for other go from QA?

The validation with the RPM in staging which is running now.

**Comment by r0ckarong** [comment]
Waiting for QA greenlight for 4.2.0

**Pull request merged**
