### PR TITLE
[wip] 389ds changes

### PR DESCRIPTION
**Pull request by cclhsu**
- Instance name hard code to localhost to consist with upstream so user can migrate directory data to newer version.
- Align filter group  to use "groupOfNames" so examples can be used between different sections of documents. 
- make variable consist with changes in 389ds entrypoint.
- Add reference to apply and access dex.yaml for examples

### CODE REVIEW

**Comment by Martin-Weiss** [comment]
Why is it required to use the instance name "localhost"?

**Comment by cclhsu** [comment]
> Why is it required to use the instance name "localhost"?

In discussion with William Brown, to be consistent with upstream, so we can update to newer package later on.

>  You can *never* change the instance name in the container from "localhost". The "instance name" is just a tag to allow multiple instances to exist, and upstream will always call their instances localhost, so you can not allow this to be customised in any circumstances.

**Comment by Martin-Weiss** [comment]
And what happens if I need two instances with replication in different containers?
Is it valid to have the instance name identical in two different containers? In case yes - we should remove the parameter for instance name and hard code it ...

**Comment by flavio** [comment]
Please provide a description to this PR

**Comment by r0ckarong** [comment]
@cclhsu Could you please provide more description for this so we can move forward with this PR?

cc @innobead

**Comment by cclhsu** [comment]
should not merge until "389ds entrypoint" changes are check in.

**Comment by r0ckarong** [comment]
> should not merge until "389ds entrypoint" changes are check in.

@cclhsu Has this happened yet?

**Comment by cclhsu** [comment]
@r0ckarong Still having on going discussion with 389-ds Upstream on bast course of action.

**Comment by r0ckarong** [comment]
@innobead @cclhsu Is there a prediction when this can be closed? What is blocking this from being completed?

It's been in progress for quite a long time and now we're accumulating conflicts with other work. We also have several issues related to this waiting to be closed by the changes.

**Comment by innobead** [comment]
> @innobead @cclhsu Is there a prediction when this can be closed? What is blocking this from being completed?
> 
> It's been in progress for quite a long time and now we're accumulating conflicts with other work. We also have several issues related to this waiting to be closed by the changes.

This is blocked by the release process. IIRC, It was planned to do in this sprint and be released in 4.0.3. @cclhsu please confirm this and work with @jordimassaguerpla. Thanks.

**Comment by jordimassaguerpla** [comment]
@cclhsu I am putting this card in staging and labeling 4.0.3.

@maximenoel8 : I know you are testing 389ds update. Could you please check the docs as well?

@r0ckarong : Once we have the go from QA, we will create the maintenance request and then this will be ready to be merged.

**Comment by r0ckarong** [comment]
Closes: 
#496 
#497 
#598 
#605

**Comment by r0ckarong** [comment]
@innobead @cclhsu From what I understand QA has signed off on the image and this could be reviewed. Is the work on this PR done for now?

**Comment by cclhsu** [comment]
@r0ckarong I rebased the document last Friday, made sure there is no merge conflicts, and went through changes.  There is no addtional change from me.  Please review the PR.

**Comment by cclhsu** [comment]
@r0ckarong I add one additional change to clarify 389ds package known issue for replace external certificate.

**Pull request merged**
