### PR TITLE
Update deployment-cilium.adoc for Cilium 1.6

### PR DESCRIPTION
**Pull request by manuelbuil**
Change the urls to refer to Cilium 1.6.
Add the information about L7 Network Policies being implemented by Envoy
proxy

Signed-off-by: Manuel Buil <mbuil@suse.com>

# Make sure it's tested
*Technical writers will not always be able to verify the implementation!*

Any PR opened is assumed to have been verified by QA if not designated by comments or labels otherwise. Please make sure you have tested the changes and included any information that a user would require to use the documentation.

# Describe your changes
What is this PR about? Please briefly detail why this needs to be integrated
and where you think it should go if it's not obvious from the changes.

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:

# Enable maintainer updates
Please enable maintainer updates so we can push commits into your branch to make collaboration and reviews easier.

# Do not force push your branch
Please avoid force pushing to branches that are subject of pull requests. Force pushing breaks maintainer commits in many cases and is very hard (if not impossible) to untangle for backporting.

# Labels
Please set any (and all) appropriate labels that describe the status of the PR.

| **Label** | **Description** |
| --- | --- |
| P1 | PR should be worked on and merged as soon as possible |
| Blocked | Work can not proceed because other work has not been completed, PR can not be merged (code has not been merged but documentation is ready) |
| On-Hold | Underlying work is completed but the PR should not be merged |
| ReleaseNotes | User interaction is required after the introduction of this change and the change must be mentioned in the release notes |
| v3/v4/v4.x | Which version of the release the PR should be merged into, this can be multiple versions, please set the "Backport" label if it needs to go into a previous release |
| Needs Review | Some details of the PR are known to be incomplete and must be discussed with other engineers before merging (if possible assign reviewers or cc mention in comments), PR can not be merged |

### CODE REVIEW

**Comment by r0ckarong** [comment]
Looks good, can go in once Cilium 1.6 ships.

**Comment by r0ckarong** [comment]
@manuelbuil Can you clarify that CaaSP 4.2.x will ship L7 policy management? If so the Note at the top of the document needs to be changed or removed.

**Comment by r0ckarong** [comment]
>  2\. This doesn't relate to your changes, but I think that this page should be moved from `deployment` to `admin`, This page is about using network policies, not about deploying Cilium. @r0ckarong - what do you think?

Fine by me. We can move this content to admin but then we need an example on how to set up network policies during deployment of a new cluster in this file.

**Comment by manuelbuil** [comment]
> ve this content to admin but then we need an example on how to set up network policies during deplo



> > 2. This doesn't relate to your changes, but I think that this page should be moved from `deployment` to `admin`, This page is about using network policies, not about deploying Cilium. @r0ckarong - what do you think?
> 
> Fine by me. We can move this content to admin but then we need an example on how to set up network policies during deployment of a new cluster in this file.

When deploying Cilium, there are no network policies deployed. Once the deployment of Skuba (including Cilium) is finished and hence the system is up and running, user can deploy network policies. That is what we are currently describing in the `deployment-cilium.adoc` file. Therefore, there is no need to explain how to set up network policies during deployment.

Should I change the name of the file? `mv deployment-cilium.adoc admin-cilium.adoc`?

**Comment by mrostecki** [comment]
@r0ckarong 
> Fine by me. We can move this content to admin but then we need an example on how to set up network policies during deployment of a new cluster in this file.

The thing is that network policies can be set up then the whole cluster is up and running. So there is no way of applying them "during deployment". That's why I think that we should move the whole file to the Admin guide and consider creating network policies as an post-deployment operation.

**Comment by r0ckarong** [comment]
> @r0ckarong
> 
> > Fine by me. We can move this content to admin but then we need an example on how to set up network policies during deployment of a new cluster in this file.
> 
> The thing is that network policies can be set up then the whole cluster is up and running. So there is no way of applying them "during deployment". That's why I think that we should move the whole file to the Admin guide and consider creating network policies as an post-deployment operation.

Maybe the wording was confusing. The current content of "Network Policies" comes after the bootstrap and that's where I would expect an example and then a link to the respective admin guide section.

**Comment by r0ckarong** [comment]
@manuelbuil 
> Hello Markus. We are a bit confused about your expectations on https://github.com/SUSE/doc-caasp/pull/783. Network Policies have nothing to do with the bootstrap process, or at least that's what we think. Maybe you have something else in mind that we are missing 

I'm going to answer here: Michal wrote above that the policies `policies can be set up then the whole cluster is up and running.`. Since this is a security critical step for customers who want to use this (correct me if I'm mistaken here) they will want to set up policies as soon as they can. So after the regular bootstrap chapter is done and the cluster is up we should give a simple example of how to set up a policy (so someone who knows what they are doing can start immediately setting up policies) and link to the admin guide where the topic is explained in detail (so those who do NOT know what they are doing can get an understanding how to do it).

Does that make more sense now? The current section that comes after bootstrap explains the general working of policies and I agree that this fits better in the longer section that has to be created in the admin guide.

**Comment by jordimassaguerpla** [comment]
Hi. This is planned for 4.2.1. Please remember that we do not merge until we have the QA green light on Staging, which we do not have. Given you already did merge, just make a note somewhere that in case QA rejects, this will need to be removed. Thanks.

**Comment by r0ckarong** [comment]
These were all merged to a feature branch (cilium-docs-updates) so I can just merge the other branch once this is ready.

**Comment by manuelbuil** [comment]
> Hi. This is planned for 4.2.1. Please remember that we do not merge until we have the QA green light on Staging, which we do not have. Given you already did merge, just make a note somewhere that in case QA rejects, this will need to be removed. Thanks.

thanks @jordimassaguerpla , I thought it was enough that QA gives his blessing with the Cilium PR https://github.com/SUSE/skuba/pull/1012.  The QA tests in Staging are checking that the "new" Cilium does not create any regression problem? Can you pass us the link to track those staging tests please?

**Comment by jordimassaguerpla** [comment]
Hi Manuel,
QA blessing is enough to merge and proceed with the inclusion of the packages into staging.

However, based on the CaaSP history, I asked Doc Team to not merge the docs until QA has verified staging, so in case we found a regression we could remove the feature from staging.

For every staging there is a job that the release team will trigger. Staging for 4.2.1 does not  yet include the skuba package and so the job is not yet triggered.

You can see, as an example, the job for 4.2.0 here:

https://ci.suse.de/view/CaaSP/view/Dashboard%20v4%20Dashboard/job/caasp-jobs/job/validation/job/caasp-v4-staging-precheck/ 

See the parameters that was the last job run.

**Pull request merged**
