### PR TITLE
Add instruction on how to fix invalid client secret (bsc#1173055)

### PR DESCRIPTION
**Pull request by jenting**
# Describe your changes

Add instructions on how to fix invalid client secret before and after skuba 4.2.2 separately.
This PR is for maintenance/CaaS4.5 branch.

I realized that #899 is not included in the current master branch, so I cherry-pick it from maintenance/CaaS4 branch.

# Related Issues / Projects

Relates to: bsc#1173055

### CODE REVIEW

**Comment by r0ckarong** [comment]
Could you rebase this to `maintenance/CaaS4.5`?

**Comment by jenting** [comment]
> Could you rebase this to `maintenance/CaaS4.5`?

Oops, I choose the wrong base branch, updated.

**Comment by jenting** [comment]
@r0ckarong why do we have branch `maintenance/CaaS4.5`? Isn't the current `master` branch means `4.5` already?

**Comment by r0ckarong** [comment]
> @r0ckarong why do we have branch `maintenance/CaaS4.5`? Isn't the current `master` branch means `4.5` already?

We sometimes need to update the previous version, say development on `master` shifts to 4.6.x, we still need to maintain 4.5.x.
At this point in the development `master` and `maintenance/CaaS4.5` are the same but this can change at any point due to political decisions.

We basically maintain (at least) three versions of the product at this point: 

- `master` (ongoing 4.5.x work)
- `maintenance/CaaS4` (4.2.x)
- `maintenance/CaaS4.5` (4.5.0 released version)

In theory, we also have a 4.1 for SAP version but I haven't had to do any updates on those docs and I dread the day when I will be asked to ...

**Comment by jenting** [comment]
> > @r0ckarong why do we have branch `maintenance/CaaS4.5`? Isn't the current `master` branch means `4.5` already?
> 
> We sometimes need to update the previous version, say development on `master` shifts to 4.6.x, we still need to maintain 4.5.x.
> At this point in the development `master` and `maintenance/CaaS4.5` are the same but this can change at any point due to political decisions.
> 
> We basically maintain (at least) three versions of the product at this point:
> 
> * `master` (ongoing 4.5.x work)
> * `maintenance/CaaS4` (4.2.x)
> * `maintenance/CaaS4.5` (4.5.0 released version)
> 
> In theory, we also have a 4.1 for SAP version but I haven't had to do any updates on those docs and I dread the day when I will be asked to ...

It'd would be good to write this in the PR template or README :smile:

**Comment by r0ckarong** [comment]
This is a duplicate of #1000 and I will cherry pick this manually to 4.5

**Pull request closed without merging**
