### PR TITLE
Remove wrong description for worker

### PR DESCRIPTION
**Pull request by jhsiaosuse**
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by r0ckarong** [comment]
@jhsiaosuse Could you please confirm why this note is no longer true? Will the specified username be created on the system automatically?

**Comment by jhsiaosuse** [comment]
> @jhsiaosuse Could you please confirm why this note is no longer true? Will the specified username be created on the system automatically?

It's wired behind `workers`.

image

**Comment by jhsiaosuse** [comment]
Okay... I think due to OpenStack terraform script removes the username field, so that why I saw it looks strange.

But VMware terraform script still keeps it.

**Comment by r0ckarong** [comment]
> Okay... I think due to OpenStack terraform script removes the username field, so that why I saw it looks strange.
> 
> But VMware terraform script still keeps it.

Aahh, now I understand this. It's a remnant from a removed option. I totally misread the commit. You are right to remove this. My bad. Will merge.

**Pull request merged**
