### PR TITLE
Updated "Services on Nodes" diagram (fig 1.2) (BSC#1093559)

### PR DESCRIPTION
**Pull request by lproven**
Got new PNG from Alvaro Saurin.

Removed old, outdated SVG file. Added new PNG instead. Updated Deployment Guide to reference new image.

### CODE REVIEW

**Comment by lproven** [comment]
Source of new diagram: https://github.com/kubic-project/salt/pull/637

**Comment by lproven** [comment]
You will have to ask Alvaro Saurin... https://github.com/inercia

**Comment by lproven** [comment]
This is the bug where he logged the issue: https://bugzilla.suse.com/show_bug.cgi?id=1093559

**Comment by r0ckarong** [comment]
Ah ok, then nevermind. That bug report is pretty clear.

**Comment by lproven** [comment]
As Alvaro has now given me access to the Google Docs repo, I have replaced the PNG file with an SVG version instead.

**Pull request merged**
