### PR TITLE
VCP CPI enabled will disable hostname from DHCP

### PR DESCRIPTION
**Pull request by c3y1huang**
# Describe your changes
Address to fix in https://github.com/SUSE/skuba/pull/1326#event-3669162508.
When vSphere CPI enabled will automatically disable the VM hostname DHCP server assignment.

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to: https://github.com/SUSE/avant-garde/issues/1817

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Comment by innobead** [comment]
> @jordimassaguerpla Which version release will this skuba change be in?

It depends on if https://github.com/SUSE/skuba/pull/1326#event-3669162508 will be backported or not. Leave @cclhsu to discuss with the release group.

**Comment by r0ckarong** [comment]
@innobead @cclhsu any updates?

**Comment by innobead** [comment]
> @innobead @cclhsu This has been backported now apparently, any updates if we can merge this for 4.5.1?

From my view, yes. But let @cclhsu help handle this. Thanks.

**Comment by cclhsu** [comment]
I believe it was agreed on last Monday Release Coordination meeting to be included in 4.5.2.

**Pull request merged**
