### PR TITLE
Add kubelet.conf warning message for k8s version < 1.17 (bsc#1176578)

### PR DESCRIPTION
**Pull request by jenting**
# Describe your changes

The kubelet.conf has a bug if the node is bootstrapped/joined before
Kubernetes version < 1.17, the kubelet.conf did not point to the
automatically rotated kubelet client certificate.

Also, add the client certificate embedded in the KUBECONFIG files used
by kubeadm, which are
- admin.conf
- controller-manager.conf
- scheduler.conf
- kubelet.conf

# Related Issues / Projects

Relates to: bsc#1176578
xrefs to: https://github.com/SUSE/avant-garde/issues/1961

### CODE REVIEW

**Comment by jenting** [comment]
This PR needs to backport.

**Comment by jordimassaguerpla** [comment]
Is this related to a PR in skuba or a package fix? Or do these docs can be released alone?

**Comment by jenting** [comment]
> Is this related to a PR in skuba or a package fix? Or do these docs can be released alone?

Only doc PR to have a manual way to fix kubeadm prior to 1.17 issue for now.

I'll check if kubeadm or skuba could fix the issue, however, let's have a doc workaround for this.

**Review by c3y1huang — APPROVED** [review]

**Comment by jenting** [comment]
> Is this related to a PR in skuba or a package fix? Or do these docs can be released alone?

I've create a PR in skuba https://github.com/SUSE/skuba/pull/1369 to auto update kubelet.conf during node upgrade,
however, we still need to write down the manual way to tackle this if the admin does not want to upgrade their Kubernetes cluster and this PR is for the purpose.

**Review by innobead — APPROVED** [review]
LGTM!

**Pull request merged**
