### PR TITLE
Better wording for Velero chapter

### LINKED ISSUE #865: Backup/Restore section wording
Not sure if this has been addressed...apologies if it has. I didn't look at all the pull requests.

Both 9.4 and 9.5 are quite confusing. Shouldn't the installation be the same no matter where CaaSP is running?
For starters..."on on-premise" probably is not a proper statement.
It seems the titles are misleading a bit. No need to state "Kubernetes cluster". It would be the CaaSP Cluster, right?
The titles on all of the sections are misleading...
9.4.1 should read something like Backup Kubernetes objects only
9.4.1.1 should read Backup to a Cloud Provider
9.4.2 shoud read something like Backup Kubernetes objects and Volumes to Cloud Provider. Velero will backup using the provider snapshot capability to backup the volumes (aws ebs snapshots or use restic for snapshots)
The diff in these are simply the volume snapshot.
9.5 seems redundant because it won't matter where CaaSP is run. The backup process will be the same

9.4  Deployment On On-Premise:

https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_deployment_on_on_premise

### PR DESCRIPTION
**Pull request by jenting**
# Describe your changes

1. Consolidate two deployment docs into one.
2. Decrease the sub-chapter usage to make it legibility
3. Format alignments

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

fixed #865

### CODE REVIEW

**Comment by jenting** [comment]
Merge remote-tracking branch 'upstream/maintenance/CaaS4'

**Comment by nkoranova** [comment]
I think this looks good now, but since @r0ckarong has assigned it to himself, I'm going to wait for him to have a quick look at it before I merge it. :angel:

**Comment by nkoranova** [comment]
On second thought Markus is off this week too, so I'm going to merge this. :)

**Comment by nkoranova** [comment]
cherry picked to master https://github.com/SUSE/doc-caasp/commit/d9d5dc35e889242c027bba724739280366e43024

**Pull request merged**
