### PR TITLE
fix https://github.com/SUSE/avant-garde/issues/1294

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
fix https://github.com/SUSE/avant-garde/issues/1294

### CODE REVIEW

**Comment by r0ckarong** [comment]
@jordimassaguerpla Please make sure to always enable "maintainer updates" in your PR so I can push commits directly to your proposed branch.

**Comment by nkoranova** [comment]
edited and merged with https://github.com/SUSE/doc-caasp/commit/e1d1a17d566c8a65c46cc03b51b3087782791340

**Comment by jordimassaguerpla** [comment]
@nkoranova : can we have it backported to the release 4.1.1 branch?

**Comment by nkoranova** [comment]
@jordimassaguerpla already done by @r0ckarong here: https://github.com/SUSE/doc-caasp/pull/701

**Pull request closed without merging**
