### PR TITLE
Add etcd cluster backup intro

### PR DESCRIPTION
**Pull request by c3y1huang**
# Make sure it's tested
n/a

# Describe your changes
Brief intro to etcd cluster backup

# Related Issues / Projects

Relates to: https://github.com/SUSE/doc-caasp/issues/801

# Enable maintainer updates
Please enable maintainer updates so we can push commits into your branch to make collaboration and reviews easier.

# Do not force push your branch
Please avoid force pushing to branches that are subject of pull requests. Force pushing breaks maintainer commits in many cases and is very hard (if not impossible) to untangle for backporting.

# Labels
Please set any (and all) appropriate labels that describe the status of the PR.

| **Label** | **Description** |
| --- | --- |
| P1 | PR should be worked on and merged as soon as possible |
| Blocked | Work can not proceed because other work has not been completed, PR can not be merged (code has not been merged but documentation is ready) |
| On-Hold | Underlying work is completed but the PR should not be merged |
| ReleaseNotes | User interaction is required after the introduction of this change and the change must be mentioned in the release notes |
| v3/v4/v4.x | Which version of the release the PR should be merged into, this can be multiple versions, please set the "Backport" label if it needs to go into a previous release |
| Needs Review | Some details of the PR are known to be incomplete and must be discussed with other engineers before merging (if possible assign reviewers or cc mention in comments), PR can not be merged |

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

### CODE REVIEW

**Comment by nkoranova** [comment]
That was amazingly quick, thanks! 

I just have one comment/question: Since etcd cluster backup is recommended to ensure trouble-free operation of Velero, should we place this chapter ahead of the Velero chapter?

**Comment by c3y1huang** [comment]
> That was amazingly quick, thanks!
> 
> I just have one comment/question: Since etcd cluster backup is recommended to ensure trouble-free operation of Velero, should we place this chapter ahead of the Velero chapter?

I don't have strong opinions about this but move this chapter ahead make sense to me to improve the read flow.

**Comment by nkoranova** [comment]
Ok, I'm happy with this now, we can merge it.

**Comment by innobead** [comment]
Thanks for the cooperation @nkoranova @c3y1huang :+1:

**Pull request merged**
