### PR TITLE
Enhance terraform vsphere_resource_pool details

### PR DESCRIPTION
**Pull request by c3y1huang**
# Make sure it's tested
N/A

# Describe your changes
Sync vsphere_resource_pool example with with terraform site, xref: https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html.
Add reference link to vsphere resource pool details

# Related Issues / Projects

Relates to: https://github.com/SUSE/doc-caasp/issues/794

# Enable maintainer updates
Please enable maintainer updates so we can push commits into your branch to make collaboration and reviews easier.

# Do not force push your branch
Please avoid force pushing to branches that are subject of pull requests. Force pushing breaks maintainer commits in many cases and is very hard (if not impossible) to untangle for backporting.

# Labels
Please set any (and all) appropriate labels that describe the status of the PR.

| **Label** | **Description** |
| --- | --- |
| P1 | PR should be worked on and merged as soon as possible |
| Blocked | Work can not proceed because other work has not been completed, PR can not be merged (code has not been merged but documentation is ready) |
| On-Hold | Underlying work is completed but the PR should not be merged |
| ReleaseNotes | User interaction is required after the introduction of this change and the change must be mentioned in the release notes |
| v3/v4/v4.x | Which version of the release the PR should be merged into, this can be multiple versions, please set the "Backport" label if it needs to go into a previous release |
| Needs Review | Some details of the PR are known to be incomplete and must be discussed with other engineers before merging (if possible assign reviewers or cc mention in comments), PR can not be merged |

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

### CODE REVIEW

**Comment by r0ckarong** [comment]
@jordimassaguerpla The vSphere topic now just needs your OK after QA. Please let me know when this can be merged.

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla The vSphere topic now just needs your OK after QA. Please let me know when this can be merged.

When QA give us the ok from Staging 4.2.1.

**Comment by jordimassaguerpla** [comment]
> > @jordimassaguerpla The vSphere topic now just needs your OK after QA. Please let me know when this can be merged.
> 
> When QA give us the ok from Staging 4.2.1.

Meaning Martin or Tomas .... but Staging 4.2.1 is not yet passing the precheck tests, so they cannot give you the :+1: yet

**Comment by r0ckarong** [comment]
> > > @jordimassaguerpla The vSphere topic now just needs your OK after QA. Please let me know when this can be merged.
> > 
> > 
> > When QA give us the ok from Staging 4.2.1.
> 
> Meaning Martin or Tomas .... but Staging 4.2.1 is not yet passing the precheck tests, so they cannot give you the +1 yet

I meant tell me when we have the thumbs up :)

**Comment by jordimassaguerpla** [comment]
> > > > @jordimassaguerpla The vSphere topic now just needs your OK after QA. Please let me know when this can be merged.
> > > 
> > > 
> > > When QA give us the ok from Staging 4.2.1.
> > 
> > 
> > Meaning Martin or Tomas .... but Staging 4.2.1 is not yet passing the precheck tests, so they cannot give you the +1 yet
> 
> I meant tell me when we have the thumbs up :)

sure :)

**Pull request merged**
