### PR TITLE
[WIP] Add documentation for the ability to set the datastore_cluster vmware/TF

### PR DESCRIPTION
**Pull request by dirkmueller**
# Make sure it's tested
*Technical writers will not always be able to verify the implementation!*

Any PR opened is assumed to have been verified by QA if not designated by comments or labels otherwise. Please make sure you have tested the changes and included any information that a user would require to use the documentation.

# Describe your changes
What is this PR about? Please briefly detail why this needs to be integrated
and where you think it should go if it's not obvious from the changes.

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:

# Enable maintainer updates
Please enable maintainer updates so we can push commits into your branch to make collaboration and reviews easier.

# Do not force push your branch
Please avoid force pushing to branches that are subject of pull requests. Force pushing breaks maintainer commits in many cases and is very hard (if not impossible) to untangle for backporting.

# Labels
Please set any (and all) appropriate labels that describe the status of the PR.

| **Label** | **Description** |
| --- | --- |
| P1 | PR should be worked on and merged as soon as possible |
| Blocked | Work can not proceed because other work has not been completed, PR can not be merged (code has not been merged but documentation is ready) |
| On-Hold | Underlying work is completed but the PR should not be merged |
| ReleaseNotes | User interaction is required after the introduction of this change and the change must be mentioned in the release notes |
| v3/v4/v4.x | Which version of the release the PR should be merged into, this can be multiple versions, please set the "Backport" label if it needs to go into a previous release |
| Needs Review | Some details of the PR are known to be incomplete and must be discussed with other engineers before merging (if possible assign reviewers or cc mention in comments), PR can not be merged |

### CODE REVIEW

**Comment by r0ckarong** [comment]
@dirkmueller Is there more coming in this PR or is the work finished?

**Comment by r0ckarong** [comment]
@dirkmueller Can I merge this? It's still labelled as "WIP"?

**Comment by dirkmueller** [comment]
@r0ckarong why did you merge this already? The code change this change is documents isnt merged and it was marked as WIP..

**Comment by r0ckarong** [comment]
> @r0ckarong why did you merge this already? The code change this change is documents isnt merged and it was marked as WIP..

Sorry my bad. Since I didn't get a response from you in over a month I assumed you abandoned this.

**Pull request merged**
